version: "3.8"
services:
  backend:
    image: auth-user:${TAG}
    container_name: auth-user
    hostname: auth-user-{{.Task.Slot}}
    env_file:
      - .env
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: "0.80"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      endpoint_mode: vip
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress
    networks:
      - auth-user-network

networks:
  auth-user-network:
    driver: overlay
    attachable: true
