name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Create .env file dynamically
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          HOST=${{ secrets.HOST }}
          NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GIN_MODE=${{ secrets.GIN_MODE }}
          TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
          EOF
        shell: bash

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --build-arg PORT="${{ secrets.PORT }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg HOST="${{ secrets.HOST }}" \
            --build-arg NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
            --build-arg GIN_MODE="${{ secrets.GIN_MODE }}" \
            --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --build-arg TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}" \
            --build-arg TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
            -t backend-user:${{ github.run_number }} .

      - name: Verify Docker Image Exists
        run: docker images | grep backend-user

      - name: Save Image as tar
        run: docker save -o backend-user-${{ github.run_number }}.tar backend-user:${{ github.run_number }}

      - name: Transfer image and .env to VPS
        run: |
          scp -o StrictHostKeyChecking=no backend-user-${{ github.run_number }}.tar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/backend-user/
          scp -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/backend-user/

      - name: Deploy image to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/backend-user
            export TAG=${{ github.run_number }}  # Set the TAG variable
            docker load -i backend-user-${{ github.run_number }}.tar
            docker stack deploy --compose-file docker-compose.yml backend-user
          EOF
