name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Create environment file
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          HOST=${{ secrets.HOST }}
          NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GIN_MODE="release"
          TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
          EOF
        shell: bash

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Build Image
        run: |
          docker buildx build \
            --build-arg PORT="${{ secrets.PORT }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg HOST="${{ secrets.HOST }}" \
            --build-arg NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
            --build-arg GIN_MODE="release" \
            --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --build-arg TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}" \
            --build-arg TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}" \
            -t auth-user:${{ github.run_number }} .

      - name: Compress artifacts
        run: docker save -o auth-user-${{ github.run_number }}.tar auth-user:${{ github.run_number }}

      - name: Copy artifacts
        run: |
          scp -o StrictHostKeyChecking=no auth-user-${{ github.run_number }}.tar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/auth-user/
          scp -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ INSTALL_PATH }}

      - name: Install and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ INSTALL_PATH }}
            export TAG=${{ github.run_number }}  # Set the TAG variable
            docker load -i auth-user-${{ github.run_number }}.tar
            docker stack deploy --compose-file docker-compose.yml auth-user
          EOF
