name: release-go

on:
  workflow_run:
    workflows: [Deployment]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  second-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build with Go
        run: |
          mkdir -p build || exit 1
          go build -ldflags="-s -w" -v -o build/auth-user . || exit 1

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: auth-user
          path: build/auth-user

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=v$(date +'%Y.%m.%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          release_name: Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/auth-user
          asset_name: auth-user-${{ steps.tag.outputs.release_tag }}
          asset_content_type: application/octet-stream
